services:
  mysql:
    image: mysql:8.0
    container_name: message-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: message_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"   # Host port 3307 -> container port 3306
    volumes:
      - message_db_data:/var/lib/mysql
    networks:
      - message-net

  backend:
    build: .
    container_name: message-api
    restart: always
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:rootpassword@mysql:3306/message_db
    networks:
      - message-net
    volumes:
      - .:/app

  client:
    build:
      context: ./client   # path to your client folder (where the Dockerfile is)
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: "http://backend:5001"   # point frontend to backend service
    container_name: message-client
    ports:
      - "8080:80"   # access React build via http://localhost:8080
    networks:
      - message-net
    depends_on:
      - backend

volumes:
  message_db_data:

networks:
  message-net:
