networks:
  onfon-net:

services:
  onfon-mysql:
    image: mysql:8.0
    container_name: onfon-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Maveke12  
      MYSQL_DATABASE: onfon_db
    networks:
      - onfon-net

  onfon-backend:
    build: .
    container_name: onfon-backend
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      DATABASE_URL: mysql+pymysql://root:Maveke12@onfon-mysql:3306/onfon_db
    ports:
      - "5000:5000"
    networks:
      - onfon-net
